source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer'
gem 'sass-rails'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'unicorn'
gem 'unicorn-rails'
gem 'broutes', git: 'git://github.com/jsimpson/broutes', ref: '501f40b'
gem 'paperclip'
gem 'bootstrap-sass'
gem 'sprockets'
gem 'autoprefixer-rails'
gem 'bootstrap_form'
gem 'haml-rails'
gem 'chartkick'
gem 'groupdate'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'gmaps4rails'
gem 'underscore-rails'

group :development, :test do
  gem 'awesome_print', require: 'ap'
  gem 'better_errors'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'meta_request'
  gem 'peek'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'rubocop'
  gem 'web-console'
  gem 'sandi_meter'
  gem 'brakeman'
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
