source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer'
gem 'sass-rails'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'unicorn'
gem 'unicorn-rails'
gem 'broutes', git: 'git://github.com/jsimpson/broutes', ref: '50d7ef3189bf151a4d32cb67b74f88883968e966'
gem 'paperclip'
gem 'bootstrap-sass'
gem 'sprockets'
gem 'autoprefixer-rails'
gem 'bootstrap_form'
gem 'haml-rails'
gem 'chartkick'
gem 'groupdate'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

group :development, :test do
  gem 'better_errors'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'rubocop'
  gem 'spring'
  gem 'web-console'
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
